title: Meteo-France AI Lab's Blog
description: Blogposts from Meteo-France AI Lab
baseurl: "/ai-lab-blog" # the subpath of your site, e.g. /blog/
# url: "https://meteofrance.github.io/"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: classic

social_links:
 - { platform: github, user_url: "https://github.com/meteofrance" }
